---
version: 2.1

executors:
  ruby_executor:
    working_directory: /mnt/ramdisk
    docker:
      - image: cimg/ruby:3.1.2-browsers
  rails_executor:
    working_directory: /mnt/ramdisk
    docker:
      - image: cimg/ruby:3.1.2-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          BUNDLE_FROZEN: true
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
          POSTGRES_HOST_AUTH_METHOD: trust
        command: postgres -c 'fsync=false' -c 'synchronous_commit=off'
    resource_class: xlarge
commands:
  install_system_dependencies:
    description: "Install system dependencies"
    steps:
      - run:
          name: install system dependencies
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo apt-get update -yqq
  install_js_dependencies:
    description: "Install JS dependencies"
    steps:
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install --frozen-lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - /mnt/ramdisk/node_modules
            - ~/.npm
  install_ruby_dependencies:
    description: "Install Ruby dependencies"
    steps:
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: install bundler & ruby dependencies
          command: |
            gem install bundler:2.3.5 --no-document && \
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [/mnt/ramdisk/vendor/bundle]
  setup_test_db:
    description: "Setup test database"
    steps:
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create db:schema:load
  setup_webdriver:
    description: Install Ruby webdriver
    steps:
      - run: date -I > /tmp/today && cat /tmp/today
      - restore_cache:
          key: webdrivers-v2-{{ checksum "/tmp/today" }}
      - run: if [ ! -f ~/.webdrivers/chromedriver ] ; then bundle exec rake webdrivers:chromedriver:update ; fi
      - save_cache:
          key: webdrivers-v2-{{ checksum "/tmp/today" }}
          paths: [~/.webdrivers]
jobs:
  run_ruby_tests:
    executor: rails_executor
    steps:
      - checkout
      - install_system_dependencies
      - install_ruby_dependencies
      - setup_test_db
      - run: bundle exec rspec
      - store_test_results:
          path: tmp/rspec-test-results
  deploy_to_aptible--staging:
    executor: ruby_executor
    steps:
      - checkout
      - run: echo $APTIBLE_PUBLIC_KEY >> ~/.ssh/known_hosts
      - run: git fetch --depth=1000000
      - run: git push git@beta.aptible.com:tax-foundational-project-2022-11/tfp-prod.git $CIRCLE_SHA1:main

    parallelism: 1

workflows:
  version: 2
  ci-and-deploy:
    jobs:
      - run_ruby_tests
      - deploy_to_aptible--staging:
          requires: [ run_ruby_tests ]
#          filters:
#            branches:
#              only: main